INSERT INTO quest_template (ID, QuestSortID, QuestInfoID, SuggestedGroupNum, Flags, LogTitle, LogDescription, QuestDescription, AreaDescription, QuestCompletionLog, QuestLevel, MinLevel, AllowableRaces, StartItem, POIx, POIy, POIContinent, TimeAllowed, RequiredPlayerKills, RewardXPDifficulty, RewardMoney, RewardSpell, RewardHonor, RewardTitle, RewardArenaPoints, RewardTalents) VALUES (60035, 0, 21, 0, 8, 'the beginning of an adventuree', 'Guard : $BI have already heard that there is a traveler who suddenly appears by summoning a group of light from somewhere. We have orders to bring you to the palace when you see some idiots like you. Plus an order to pay a horse. Traveler, I must have delivered the order clearly, right? Go to the palace when you\'re ready! But you\'d better not think about going to the palace right now. There\'s a whole bunch of scary monsters out there.$BFirst of all, be fully prepared and go on a trip... That\'s all for advice.', 'You should go to Stormwind City and meet the king in the royal palace.', '', '', 1, 1, 0, 18776, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0);
INSERT INTO quest_template_addon (SpecialFlags, PrevQuestID, NextQuestID, MaxLevel, AllowableClasses, ProvidedItemCount, SourceSpellID, ID) VALUES (0, 0, 60036, 0, 0, 1, 0, 60035);
INSERT INTO quest_offer_reward (RewardText, ID) VALUES ('You\'re finally here!$BYou\'re the adventurers from North Shire Village. Before I explain, I want you to prove your skills. When you reach level 13, come visit me again.', 60035);
INSERT INTO quest_request_items (CompletionText, ID) VALUES ('Greetings $N. How goes the quest?', 60035);

INSERT INTO quest_template (ID, QuestSortID, QuestInfoID, SuggestedGroupNum, Flags, LogTitle, LogDescription, QuestDescription, AreaDescription, QuestCompletionLog, QuestLevel, MinLevel, AllowableRaces, StartItem, POIx, POIy, POIContinent, TimeAllowed, RequiredPlayerKills, RewardXPDifficulty, RewardMoney, RewardSpell, RewardHonor, RewardTitle, RewardArenaPoints, RewardTalents) VALUES (60036, 0, 21, 0, 8, 'the king\'s request', 'Yeah, you guys?$BOh! Adventurers, you\'ve proved your credentials!!!$BNow it\'s my turn to explain why I called you.$BBefore you were summoned here, I was informed that unknown travelers were summoned along with a flock of light throughout the continent. And it was also reported that they were immortal and had tremendous fighting power. As proof of qualification, you were one of them. On your way here, you\'ve heard rumors of a huge threat to the world, haven\'t you? Now we must fight against the conspirators who are trying to intimidate AZEROTH themselves, including the struggle against other tribes. But our human power is not enough to fight them, much less to break through. Now you need to build up your strength and infiltrate the secret dungeons of those who threaten human existence and eliminate key factors. Of course, big risks require rewards. Why don\'t you come forward for the future of mankind with enough reward? If you accept, please go near the auction house in Stormwind. That\'s where MASTER SERGENT MaclureE will be waiting. Take this certificate with you.', 'Meet MASTER SERGENT MaclureE near Stormwind auction house', '', '', 13, 13, 0, 0, 0, 0, 0, 0, 0, 9, 10000, 0, 0, 0, 0, 0);
INSERT INTO quest_template_addon (SpecialFlags, PrevQuestID, NextQuestID, MaxLevel, AllowableClasses, ProvidedItemCount, SourceSpellID, ID) VALUES (0, 60035, 60037, 0, 0, 0, 0, 60036);
INSERT INTO quest_offer_reward (RewardText, ID) VALUES ('I can\'t believe me Maclure ran two jobs at this time. Actually, I have to get married right now, but how about a conspiracy that threatens the world? I can\'t believe I have to deal with adventurers when it\'s time to date .....? dumb assholes are coming.$BWell, this is a certificate issued by the king. Let\'s get some compensation first.', 60036);
INSERT INTO quest_request_items (CompletionText, ID) VALUES ('Greetings $N. How goes the quest?', 60036);
INSERT INTO quest_template (ID, QuestSortID, QuestInfoID, SuggestedGroupNum, Flags, LogTitle, LogDescription, QuestDescription, AreaDescription, QuestCompletionLog, QuestLevel, MinLevel, AllowableRaces, StartItem, POIx, POIy, POIContinent, TimeAllowed, RequiredPlayerKills, RewardXPDifficulty, RewardMoney, RewardSpell, RewardHonor, RewardTitle, RewardArenaPoints, RewardTalents) VALUES (60037, 0, 21, 0, 8, 'Meeting the Quest Girl', 'And what? Travelers nominated by the king to save the world? Well... you\'re mistaken. Already, 100 teams of travelers like you have gone through me to perform the king\'s request to all parts of the continent. Do you think the king trusted a group of travelers from the North Shire village and entrusted them with the mission of saving humanity? The king has already hired thousands of travelers in each region, and I hope you know that one of them is your traveler and you have the greatest expectation of an ant.', 'Listen to the details of the mission from her.', '', '', 13, 13, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0);
INSERT INTO quest_template_addon (SpecialFlags, PrevQuestID, NextQuestID, MaxLevel, AllowableClasses, ProvidedItemCount, SourceSpellID, ID) VALUES (0, 60036, 60038, 0, 0, 0, 0, 60037);
INSERT INTO quest_offer_reward (RewardText, ID) VALUES ('Now it\'s time for me to give you a full explanation of the tasks that I\'ve assigned to you.', 60037);
INSERT INTO quest_request_items (CompletionText, ID) VALUES ('Greetings $N. How goes the quest?', 60037);
INSERT INTO quest_template (ID, QuestSortID, QuestInfoID, SuggestedGroupNum, Flags, LogTitle, LogDescription, QuestDescription, AreaDescription, QuestCompletionLog, QuestLevel, MinLevel, AllowableRaces, StartItem, POIx, POIy, POIContinent, TimeAllowed, RequiredPlayerKills, RewardXPDifficulty, RewardMoney, RewardSpell, RewardHonor, RewardTitle, RewardArenaPoints, RewardTalents, RequiredItemId1, RequiredItemCount1, RewardItem1, RewardAmount1) VALUES (60038, 2437, 81, 0, 8, 'Ragefire Chasm', 'Now it\'s time to explain the duties of the travelers.$BLet me introduce myself first.$BI\'m Maclure , your mission manager, who will give you a mission in the future and reward you for achieving it. Let me say hello again.$BNow, since we\'re dealing with hundreds of other travelers besides you, we can\'t give you any details, but we\'re replacing them with briefing papers. And I wish you good luck.', 'Explore \"Ragefire Chasm\", eliminate the target, Please bring the sign.', '', '', 13, 13, 0, 60002, -381, -1482, 0, 0, 0, 8, 10000, 0, 0, 0, 0, 0, 60003, 1, 14156, 1);
INSERT INTO quest_template_addon (SpecialFlags, PrevQuestID, NextQuestID, MaxLevel, AllowableClasses, ProvidedItemCount, SourceSpellID, ID) VALUES (0, 60037, 60040, 0, 0, 0, 0, 60038);
INSERT INTO quest_offer_reward (RewardText, ID) VALUES ('Oh, the travelers are back, and proof of removal!!!$BCongratulations on your first mission. Here\'s your reward.', 60038);
INSERT INTO quest_request_items (CompletionText, ID) VALUES ('Greetings $N. How goes the quest?', 60038);

INSERT INTO quest_template (ID, QuestSortID, QuestInfoID, SuggestedGroupNum, Flags, LogTitle, LogDescription, QuestDescription, AreaDescription, QuestCompletionLog, QuestLevel, MinLevel, AllowableRaces, StartItem, POIx, POIy, POIContinent, TimeAllowed, RequiredPlayerKills, RewardXPDifficulty, RewardMoney, RewardSpell, RewardHonor, RewardTitle, RewardArenaPoints, RewardTalents) VALUES (60039, 0, 21, 0, 8, 'Are you still alive?', 'I waited a long time for you, World Traveler.$B(Something looks like Cabin, who I saw grossly on Diablo 2. I hope it\'s not as much of a bothersome quest as a look-alike. )$BThe king has ordered you to visit the palace if the adventurers are still alive. Go to the palace as soon as possible.', 'You meet the king of the Stormwind palace.', '', '', 15, 15, 0, 0, 0, 0, 0, 0, 0, 2, 100000, 0, 0, 0, 0, 0);
INSERT INTO quest_template_addon (SpecialFlags, PrevQuestID, NextQuestID, MaxLevel, AllowableClasses, ProvidedItemCount, SourceSpellID, ID) VALUES (0, 0, 0, 0, 0, 0, 0, 60039);
INSERT INTO quest_offer_reward (RewardText, ID) VALUES ('\"Oh the other world traveler, you\'re still alive.$BWe had a lot of meetings, but it was impressive. So I contacted him because I wanted to meet you if you were alive.$BI\'ll give you gold as a souvenir. If possible, go to the auction house with this money and buy weapons or armor. Then I hope we can meet again next time.\"', 60039);
INSERT INTO quest_request_items (CompletionText, ID) VALUES ('Greetings $N. How goes the quest?', 60039);


INSERT INTO quest_template (ID, QuestSortID, QuestInfoID, SuggestedGroupNum, Flags, LogTitle, LogDescription, QuestDescription, AreaDescription, QuestCompletionLog, QuestLevel, MinLevel, AllowableRaces, StartItem, POIx, POIy, POIContinent, TimeAllowed, RequiredPlayerKills, RewardXPDifficulty, RewardMoney, RewardSpell, RewardHonor, RewardTitle, RewardArenaPoints, RewardTalents, RequiredItemId1, RequiredItemCount1, RewardItem1, RewardAmount1) VALUES (60041, 718, 81, 0, 8, 'Wailing Caverns', 'I think this mission will be very difficult. There are a lot of travelers who have died in other missions recently, so please don\'t miss the tension. Please refer to the request form for the details of the mission.', 'Explore \"Wailing Caverns\", eliminate the targets,$BPlease bring the sign.', '', '', 20, 17, 0, 60008, 0, 0, 0, 0, 0, 2, 50000, 0, 0, 0, 0, 0, 60009, 1, 14156, 1);
INSERT INTO quest_template_addon (SpecialFlags, PrevQuestID, NextQuestID, MaxLevel, AllowableClasses, ProvidedItemCount, SourceSpellID, ID) VALUES (0, 60040, 60042, 0, 0, 1, 0, 60041);
INSERT INTO quest_offer_reward (RewardText, ID) VALUES ('Oh, you\'re back safe.$BCongratulations on your third mission success. Here\'s your reward.', 60041);
INSERT INTO quest_request_items (CompletionText, ID) VALUES ('Greetings $N. How goes the quest?', 60041);

INSERT INTO quest_template (ID, QuestSortID, QuestInfoID, SuggestedGroupNum, Flags, LogTitle, LogDescription, QuestDescription, AreaDescription, QuestCompletionLog, QuestLevel, MinLevel, AllowableRaces, StartItem, POIx, POIy, POIContinent, TimeAllowed, RequiredPlayerKills, RewardXPDifficulty, RewardMoney, RewardSpell, RewardHonor, RewardTitle, RewardArenaPoints, RewardTalents, RequiredItemId1, RequiredItemCount1, RewardItem1, RewardAmount1) VALUES (60042, 209, 81, 0, 8, 'Shadowfang Keep', 'I hope you come back safely again. You seem to have a different feeling than other travelers. It\'s hard to pinpoint, but... Please read the mission carefully and leave.', 'Explore \"Shadowfang Keep\", eliminate the targets, Please bring the sign.', '', '', 22, 19, 0, 60011, -228, 2111, 33, 0, 0, 4, 50000, 0, 0, 0, 0, 0, 60012, 1, 14156, 1);
INSERT INTO quest_template_addon (SpecialFlags, PrevQuestID, NextQuestID, MaxLevel, AllowableClasses, ProvidedItemCount, SourceSpellID, ID) VALUES (0, 60041, 60043, 0, 0, 1, 0, 60042);

INSERT INTO quest_offer_reward (RewardText, ID) VALUES ('You came back safely again.$BI feel like you\'ve already been to this dungeon before, unlike some other travelers.$BMaybe It\'s my misunderstanding. Here\'s your reward.', 60042);
INSERT INTO quest_request_items (CompletionText, ID) VALUES ('Greetings $N. How goes the quest?', 60042);

INSERT INTO quest_template (ID, QuestSortID, QuestInfoID, SuggestedGroupNum, Flags, LogTitle, LogDescription, QuestDescription, AreaDescription, QuestCompletionLog, QuestLevel, MinLevel, AllowableRaces, StartItem, POIx, POIy, POIContinent, TimeAllowed, RequiredPlayerKills, RewardXPDifficulty, RewardMoney, RewardSpell, RewardHonor, RewardTitle, RewardArenaPoints, RewardTalents, RequiredItemId1, RequiredItemCount1) VALUES (60043, 719, 81, 0, 8, 'Blackfathom Deeps', 'I heard that this mission is to deal with the ancient monsters raised by the ancient gods. You said the difficulty of the previous mission was considerable. I think the future missions will be even more challenging, so please make sure to prepare for the equipment purchase at auction in advance.', 'Explore \"Blackfathom Deeps\", eliminate the targets, Please bring the sign.', '', '', 24, 21, 0, 60014, 0, 0, 0, 0, 0, 4, 100000, 0, 0, 0, 0, 0, 60015, 1);
INSERT INTO quest_template_addon (SpecialFlags, PrevQuestID, NextQuestID, MaxLevel, AllowableClasses, ProvidedItemCount, SourceSpellID, ID) VALUES (0, 60042, 60044, 0, 0, 1, 0, 60043);
INSERT INTO quest_offer_reward (RewardText, ID) VALUES ('That\'s amazing!!! Eliminate the Ancient Monsters. I\'m looking forward to the future. Oh, here\'s your reward.', 60043);
INSERT INTO quest_request_items (CompletionText, ID) VALUES ('Greetings $N. How goes the quest?', 60043);

INSERT INTO quest_template (ID, QuestSortID, QuestInfoID, SuggestedGroupNum, Flags, LogTitle, LogDescription, QuestDescription, AreaDescription, QuestCompletionLog, QuestLevel, MinLevel, AllowableRaces, StartItem, POIx, POIy, POIContinent, TimeAllowed, RequiredPlayerKills, RewardXPDifficulty, RewardMoney, RewardSpell, RewardHonor, RewardTitle, RewardArenaPoints, RewardTalents, RequiredItemId1, RequiredItemCount1) VALUES (60044, 717, 81, 0, 8, 'Stormwind Stockade', 'This mission is an underground prison in Stormwind Castle, where you are now located. Riots have been triggered by someone\'s instructions and if not quelled quickly, the aftermath will lead the entire city to chaos. Go straight to the dungeon and familiarize yourself with the mission on your way.', 'Eliminate the rioters in Stormwind\'s underground prison and remove the leader and bring the sign.', '', '', 26, 23, 0, 60017, 0, 0, 0, 0, 0, 7, 70000, 0, 0, 0, 0, 0, 60018, 1);
INSERT INTO quest_template_addon (SpecialFlags, PrevQuestID, NextQuestID, MaxLevel, AllowableClasses, ProvidedItemCount, SourceSpellID, ID) VALUES (0, 60043, 60045, 0, 0, 1, 0, 60044);
INSERT INTO quest_offer_reward (RewardText, ID) VALUES ('Travelers have been able to prevent the great chaos that could be felt inside Stormwind Castle. Thank you on behalf of everyone. And here\'s the reward.', 60044);
INSERT INTO quest_request_items (CompletionText, ID) VALUES ('Greetings $N. How goes the quest?', 60044);

INSERT INTO quest_template (ID, QuestSortID, QuestInfoID, SuggestedGroupNum, Flags, LogTitle, LogDescription, QuestDescription, AreaDescription, QuestCompletionLog, QuestLevel, MinLevel, AllowableRaces, StartItem, POIx, POIy, POIContinent, TimeAllowed, RequiredPlayerKills, RewardXPDifficulty, RewardMoney, RewardSpell, RewardHonor, RewardTitle, RewardArenaPoints, RewardTalents, RequiredItemId1, RequiredItemCount1) VALUES (60045, 491, 81, 0, 8, 'Razorfen Kraul', 'Why do the wild boars that didn\'t invade each other? If there are still travelers who do not read the mission manual and aim recklessly at the dungeon, please read carefully and carry out the mission.', 'Explore \"Razorfen Kraul\", eliminate the targets,$BPlease bring the sign.', '', '', 28, 25, 0, 60020, 0, 0, 0, 0, 0, 7, 70000, 0, 0, 0, 0, 0, 60021, 1);
INSERT INTO quest_template_addon (SpecialFlags, PrevQuestID, NextQuestID, MaxLevel, AllowableClasses, ProvidedItemCount, SourceSpellID, ID) VALUES (0, 60044, 60046, 0, 0, 1, 0, 60045);
INSERT INTO quest_offer_reward (RewardText, ID) VALUES ('I heard that you have already completed your mission safely before you came. That\'s amazing. Oh, and here\'s your reward.', 60045);
INSERT INTO quest_request_items (CompletionText, ID) VALUES ('Greetings $N. How goes the quest?', 60045);

INSERT INTO quest_template (ID, QuestSortID, QuestInfoID, SuggestedGroupNum, Flags, LogTitle, LogDescription, QuestDescription, AreaDescription, QuestCompletionLog, QuestLevel, MinLevel, AllowableRaces, StartItem, POIx, POIy, POIContinent, TimeAllowed, RequiredPlayerKills, RewardXPDifficulty, RewardMoney, RewardSpell, RewardHonor, RewardTitle, RewardArenaPoints, RewardTalents, RequiredItemId1, RequiredItemCount1) VALUES (60046, 721, 81, 0, 8, 'Gnomeregan', 'Have you ever heard of Gnomes who took refuge near Iron Forge? The Gnome that cannot be left out in the fight against Sculges is panicked. Please come and put this confusion to rest.', 'Explore the machine city of Gnom, remove your goals, and bring the signs.', '', '', 31, 28, 0, 60023, 0, 0, 0, 0, 0, 4, 80000, 0, 0, 0, 0, 0, 60024, 1);
INSERT INTO quest_template_addon (SpecialFlags, PrevQuestID, NextQuestID, MaxLevel, AllowableClasses, ProvidedItemCount, SourceSpellID, ID) VALUES (0, 60045, 60047, 0, 0, 1, 0, 60046);
INSERT INTO quest_offer_reward (RewardText, ID) VALUES ('Now that you\'ve taken care of the traitor\'s head, all you have to do is clean up. I was amazed by his amazing performance. Here\'s your reward.', 60046);
INSERT INTO quest_request_items (CompletionText, ID) VALUES ('Greetings $N. How goes the quest?', 60046);

INSERT INTO quest_template (ID, QuestSortID, QuestInfoID, SuggestedGroupNum, Flags, LogTitle, LogDescription, QuestDescription, AreaDescription, QuestCompletionLog, QuestLevel, MinLevel, AllowableRaces, StartItem, POIx, POIy, POIContinent, TimeAllowed, RequiredPlayerKills, RewardXPDifficulty, RewardMoney, RewardSpell, RewardHonor, RewardTitle, RewardArenaPoints, RewardTalents, RequiredItemId1, RequiredItemCount1) VALUES (60047, 796, 81, 0, 8, 'Scarlet Monastery', 'It\'s a shame for us humans. Take your own eyes to see if they are simply fanatics or if another plot is intertwined.', 'Crush the Red Crusades and bring a sign', '', '', 34, 31, 0, 60026, 0, 0, 0, 0, 0, 4, 90000, 0, 0, 0, 0, 0, 60027, 1);

INSERT INTO quest_template_addon (SpecialFlags, PrevQuestID, NextQuestID, MaxLevel, AllowableClasses, ProvidedItemCount, SourceSpellID, ID) VALUES (0, 60046, 60048, 0, 0, 1, 0, 60047);
INSERT INTO quest_offer_reward (RewardText, ID) VALUES ('Were the fanatics puppets, too? That\'s creepy. Please get compensation first.', 60047);
INSERT INTO quest_request_items (CompletionText, ID) VALUES ('Greetings $N. How goes the quest?', 60047);

INSERT INTO quest_template (ID, QuestSortID, QuestInfoID, SuggestedGroupNum, Flags, LogTitle, LogDescription, QuestDescription, AreaDescription, QuestCompletionLog, QuestLevel, MinLevel, AllowableRaces, StartItem, POIx, POIy, POIContinent, TimeAllowed, RequiredPlayerKills, RewardXPDifficulty, RewardMoney, RewardSpell, RewardHonor, RewardTitle, RewardArenaPoints, RewardTalents, RequiredItemId1, RequiredItemCount1, RewardItem1, RewardAmount1) VALUES (60048, 722, 81, 0, 8, 'Razorfen Downs', 'The timing was delayed by fanatics. But we\'re still judging that it\'s reversible. When you\'re ready, please leave for the capital of the wild boar species.', 'Explore \"Razorfen Downs\", eliminate the targets,$BPlease bring the sign.', '', '', 37, 34, 0, 60029, 0, 0, 0, 0, 0, 4, 120000, 0, 0, 0, 0, 0, 60030, 1, 18796, 1);
INSERT INTO quest_template_addon (SpecialFlags, PrevQuestID, NextQuestID, MaxLevel, AllowableClasses, ProvidedItemCount, SourceSpellID, ID) VALUES (0, 60047, 60049, 0, 0, 1, 0, 60048);
INSERT INTO quest_offer_reward (RewardText, ID) VALUES ('I heard that Thralll was able to breathe thanks to you. There\'s a thank you from Sral and a present.', 60048);
INSERT INTO quest_request_items (CompletionText, ID) VALUES ('Greetings $N. How goes the quest?', 60048);

INSERT INTO quest_template (ID, QuestSortID, QuestInfoID, SuggestedGroupNum, Flags, LogTitle, LogDescription, QuestDescription, AreaDescription, QuestCompletionLog, QuestLevel, MinLevel, AllowableRaces, StartItem, POIx, POIy, POIContinent, TimeAllowed, RequiredPlayerKills, RewardXPDifficulty, RewardMoney, RewardSpell, RewardHonor, RewardTitle, RewardArenaPoints, RewardTalents, RequiredItemId1, RequiredItemCount1, RewardItem1, RewardAmount1) VALUES (60049, 1337, 81, 0, 8, 'Uldaman', 'In the midst of the chaos of the continent of AZEROTH, the digging mania(dwarf) dug out the ancient city of Titan. Please hurry to ULDAMA before The Dark Irons acquires the ancient relics.$B$BAnd go to GMISLAND and buy a STAFF OF PREHISOTRIIA from an old man (Cane?)', 'Go to \"ULDAMAN\", the ancient city of Titan and where the background of Dwarf\'s birth is hidden, and complete your mission. (Requires a sign of elimination.)', '', '', 40, 37, 0, 60032, 0, 0, 0, 0, 0, 4, 200000, 0, 0, 0, 0, 0, 60033, 1, 51809, 1);
INSERT INTO quest_template_addon (SpecialFlags, PrevQuestID, NextQuestID, MaxLevel, AllowableClasses, ProvidedItemCount, SourceSpellID, ID) VALUES (0, 60048, 26050, 0, 0, 1, 0, 60049);
INSERT INTO quest_offer_reward (RewardText, ID) VALUES ('I\'m telling you, the digging mania(dwarf) keep the accident going. Thank you for your efforts. This is the only reward I can give you because of the lack of budget.$BOh, we found this in the ruins. I\'m going to give you this.', 60049);
INSERT INTO quest_request_items (CompletionText, ID) VALUES ('Greetings $N. How goes the quest?', 60049);

INSERT INTO creature_queststarter (id, quest) VALUES (90032, 60035);
INSERT INTO creature_questender (id, quest) VALUES (90032, 60035);
INSERT INTO creature_queststarter (id, quest) VALUES (90032, 60036);
INSERT INTO creature_questender (id, quest) VALUES (90032, 60036);
INSERT INTO creature_queststarter (id, quest) VALUES (90032, 60037);
INSERT INTO creature_questender (id, quest) VALUES (90032, 60037);
INSERT INTO creature_queststarter (id, quest) VALUES (90032, 60038);
INSERT INTO creature_questender (id, quest) VALUES (90032, 60038);
INSERT INTO creature_queststarter (id, quest) VALUES (90032, 60039);
INSERT INTO creature_questender (id, quest) VALUES (90032, 60039);
INSERT INTO creature_queststarter (id, quest) VALUES (90032, 60041);
INSERT INTO creature_questender (id, quest) VALUES (90032, 60041);
INSERT INTO creature_queststarter (id, quest) VALUES (90032, 60042);
INSERT INTO creature_questender (id, quest) VALUES (90032, 60042);
INSERT INTO creature_queststarter (id, quest) VALUES (90032, 60043);
INSERT INTO creature_questender (id, quest) VALUES (90032, 60044);
INSERT INTO creature_queststarter (id, quest) VALUES (90032, 60044);
INSERT INTO creature_questender (id, quest) VALUES (90032, 60045);
INSERT INTO creature_queststarter (id, quest) VALUES (90032, 60045);
INSERT INTO creature_queststarter (id, quest) VALUES (90032, 60046);
INSERT INTO creature_questender (id, quest) VALUES (90032, 60046);
INSERT INTO creature_queststarter (id, quest) VALUES (90032, 60047);
INSERT INTO creature_questender (id, quest) VALUES (90032, 60047);
INSERT INTO creature_queststarter (id, quest) VALUES (90032, 60048);
INSERT INTO creature_questender (id, quest) VALUES (90032, 60048);
INSERT INTO creature_queststarter (id, quest) VALUES (90032, 60049);
INSERT INTO creature_questender (id, quest) VALUES (90032, 60049);

