
ALTER TABLE `promotion_codes` ADD COLUMN `item_4` MEDIUMINT(8) UNSIGNED DEFAULT NULL AFTER `item_3`;
ALTER TABLE `promotion_codes` ADD COLUMN `item_5` MEDIUMINT(8) UNSIGNED DEFAULT NULL AFTER `item_4`;
ALTER TABLE `promotion_codes` ADD COLUMN `item_6` MEDIUMINT(8) UNSIGNED DEFAULT NULL AFTER `item_5`;
ALTER TABLE `promotion_codes` ADD COLUMN `item_7` MEDIUMINT(8) UNSIGNED DEFAULT NULL AFTER `item_6`;
ALTER TABLE `promotion_codes` ADD COLUMN `item_8` MEDIUMINT(8) UNSIGNED DEFAULT NULL AFTER `item_7`;
ALTER TABLE `promotion_codes` ADD COLUMN `item_9` MEDIUMINT(8) UNSIGNED DEFAULT NULL AFTER `item_8`;
ALTER TABLE `promotion_codes` ADD COLUMN `item_10`MEDIUMINT(8) UNSIGNED DEFAULT NULL AFTER `item_9`;

ALTER TABLE `promotion_codes` ADD COLUMN `item_count_4` MEDIUMINT(8) UNSIGNED DEFAULT NULL AFTER `item_count_3`;
ALTER TABLE `promotion_codes` ADD COLUMN `item_count_5` MEDIUMINT(8) UNSIGNED DEFAULT NULL AFTER `item_count_4`;
ALTER TABLE `promotion_codes` ADD COLUMN `item_count_6` MEDIUMINT(8) UNSIGNED DEFAULT NULL AFTER `item_count_5`;
ALTER TABLE `promotion_codes` ADD COLUMN `item_count_7` MEDIUMINT(8) UNSIGNED DEFAULT NULL AFTER `item_count_6`;
ALTER TABLE `promotion_codes` ADD COLUMN `item_count_8` MEDIUMINT(8) UNSIGNED DEFAULT NULL AFTER `item_count_7`;
ALTER TABLE `promotion_codes` ADD COLUMN `item_count_9` MEDIUMINT(8) UNSIGNED DEFAULT NULL AFTER `item_count_8`;
ALTER TABLE `promotion_codes` ADD COLUMN `item_count_10`MEDIUMINT(8) UNSIGNED DEFAULT NULL AFTER `item_count_9`;

