
	
ALTER TABLE `world_coded_items`
ADD COLUMN `ItemId1` BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER `ItemCount`,
ADD COLUMN `ItemCount1` BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER `ItemId1`,
ADD COLUMN `ItemId2` BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER `ItemCount1`,
ADD COLUMN `ItemCount2` BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER `ItemId2`,
ADD COLUMN `ItemId3` BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER `ItemCount2`,
ADD COLUMN `ItemCount3` BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER `ItemId3`,
ADD COLUMN `ItemId4` BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER `ItemCount3`,
ADD COLUMN `ItemCount4` BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER `ItemId4`;