DELETE FROM `trinity_string` WHERE `entry` IN (45111, 45112, 45113, 45114, 45115, 45116, 45117);
INSERT INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES
(45111, 'Battlefield {} not found.', '전장 {}을(를) 찾을 수 없습니다.', 'Champ de bataille {} introuvable.', 'Schlachtfeld {} nicht gefunden.', '战场 {} 未找到。', '戰場 {} 未找到。', 'Campo de batalla {} no encontrado.', 'Campo de batalla {} no encontrado.', 'Поле боя {} не найдено.'),
(45112, 'Battlefield {} battle started.', '전장 {} 전투가 시작되었습니다.', 'La bataille du champ de bataille {} a commencé.', 'Schlachtfeld {} Kampf gestartet.', '战场 {} 战斗已开始。', '戰場 {} 戰鬥已開始。', 'La batalla del campo de batalla {} ha comenzado.', 'La batalla del campo de batalla {} ha comenzado.', 'Сражение на поле боя {} началось.'),
(45113, 'Battlefield {} battle stopped.', '전장 {} 전투가 중지되었습니다.', 'La bataille du champ de bataille {} a été arrêtée.', 'Schlachtfeld {} Kampf beendet.', '战场 {} 战斗已停止。', '戰場 {} 戰鬥已停止。', 'La batalla del campo de batalla {} ha sido detenida.', 'La batalla del campo de batalla {} ha sido detenida.', 'Сражение на поле боя {} остановлено.'),
(45114, 'Battlefield {} factions switched.', '전장 {} 진영이 전환되었습니다.', 'Les factions du champ de bataille {} ont été échangées.', 'Schlachtfeld {} Fraktionen gewechselt.', '战场 {} 阵营已切换。', '戰場 {} 陣營已切換。', 'Las facciones del campo de batalla {} han sido intercambiadas.', 'Las facciones del campo de batalla {} han sido intercambiadas.', 'Фракции на поле боя {} переключены.'),
(45115, 'Battlefield {} timer set to {} seconds.', '전장 {} 타이머가 {}초로 설정되었습니다.', 'Le minuteur du champ de bataille {} a été réglé à {} secondes.', 'Schlachtfeld {} Timer auf {} Sekunden gesetzt.', '战场 {} 计时器已设置为 {} 秒。', '戰場 {} 計時器已設置為 {} 秒。', 'El temporizador del campo de batalla {} se ha establecido en {} segundos.', 'El temporizador del campo de batalla {} se ha establecido en {} segundos.', 'Таймер поля боя {} установлен на {} секунд.'),
(45116, 'Battlefield {} enabled.', '전장 {}이(가) 활성화되었습니다.', 'Champ de bataille {} activé.', 'Schlachtfeld {} aktiviert.', '战场 {} 已启用。', '戰場 {} 已啟用。', 'Campo de batalla {} habilitado.', 'Campo de batalla {} habilitado.', 'Поле боя {} включено.'),
(45117, 'Battlefield {} disabled.', '전장 {}이(가) 비활성화되었습니다.', 'Champ de bataille {} désactivé.', 'Schlachtfeld {} deaktiviert.', '战场 {} 已禁用。', '戰場 {} 已停用。', 'Campo de batalla {} deshabilitado.', 'Campo de batalla {} deshabilitado.', 'Поле боя {} отключено.');

