DELETE FROM `trinity_string` WHERE `entry` IN (45111, 45112, 45113, 45114, 45115, 45116, 45117);
INSERT INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES
(45111, 'Battlefield %u not found.', '전장 %u을(를) 찾을 수 없습니다.', 'Champ de bataille %u introuvable.', 'Schlachtfeld %u nicht gefunden.', '战场 %u 未找到。', '戰場 %u 未找到。', 'Campo de batalla %u no encontrado.', 'Campo de batalla %u no encontrado.', 'Поле боя %u не найдено.'),
(45112, 'Battlefield %u battle started.', '전장 %u 전투가 시작되었습니다.', 'La bataille du champ de bataille %u a commencé.', 'Schlachtfeld %u Kampf gestartet.', '战场 %u 战斗已开始。', '戰場 %u 戰鬥已開始。', 'La batalla del campo de batalla %u ha comenzado.', 'La batalla del campo de batalla %u ha comenzado.', 'Сражение на поле боя %u началось.'),
(45113, 'Battlefield %u battle stopped.', '전장 %u 전투가 중지되었습니다.', 'La bataille du champ de bataille %u a été arrêtée.', 'Schlachtfeld %u Kampf beendet.', '战场 %u 战斗已停止。', '戰場 %u 戰鬥已停止。', 'La batalla del campo de batalla %u ha sido detenida.', 'La batalla del campo de batalla %u ha sido detenida.', 'Сражение на поле боя %u остановлено.'),
(45114, 'Battlefield %u factions switched.', '전장 %u 진영이 전환되었습니다.', 'Les factions du champ de bataille %u ont été échangées.', 'Schlachtfeld %u Fraktionen gewechselt.', '战场 %u 阵营已切换。', '戰場 %u 陣營已切換。', 'Las facciones del campo de batalla %u han sido intercambiadas.', 'Las facciones del campo de batalla %u han sido intercambiadas.', 'Фракции на поле боя %u переключены.'),
(45115, 'Battlefield %u timer set to %u seconds.', '전장 %u 타이머가 %u초로 설정되었습니다.', 'Le minuteur du champ de bataille %u a été réglé à %u secondes.', 'Schlachtfeld %u Timer auf %u Sekunden gesetzt.', '战场 %u 计时器已设置为 %u 秒。', '戰場 %u 計時器已設置為 %u 秒。', 'El temporizador del campo de batalla %u se ha establecido en %u segundos.', 'El temporizador del campo de batalla %u se ha establecido en %u segundos.', 'Таймер поля боя %u установлен на %u секунд.'),
(45116, 'Battlefield %u enabled.', '전장 %u이(가) 활성화되었습니다.', 'Champ de bataille %u activé.', 'Schlachtfeld %u aktiviert.', '战场 %u 已启用。', '戰場 %u 已啟用。', 'Campo de batalla %u habilitado.', 'Campo de batalla %u habilitado.', 'Поле боя %u включено.'),
(45117, 'Battlefield %u disabled.', '전장 %u이(가) 비활성화되었습니다.', 'Champ de bataille %u désactivé.', 'Schlachtfeld %u deaktiviert.', '战场 %u 已禁用。', '戰場 %u 已停用。', 'Campo de batalla %u deshabilitado.', 'Campo de batalla %u deshabilitado.', 'Поле боя %u отключено.');

