
INSERT INTO `trinity_string` VALUES (40001,'Приветствуем вас на сервере',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Приветствуем вас на сервере');
INSERT INTO `trinity_string` VALUES (40002,'У вас не достаточно хонора для совершения покупки!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'У вас не достаточно хонора для совершения покупки!');
INSERT INTO `trinity_string` VALUES (40003,'У вас не достаточно Апа!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'У вас не достаточно Апа!');
INSERT INTO `trinity_string` VALUES (40004,'У данного персонажа уже есть такое звание!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'У данного персонажа уже есть такое звание!');
INSERT INTO `trinity_string` VALUES (40005,'Вы находитесь в бою. Чтобы использовать данного Npc выйдите из него.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Вы находитесь в бою. Чтобы использовать данного Npc выйдите из него.');
INSERT INTO `trinity_string` VALUES (40006,'Оплата Успешно Произведена Сделайте Логаут и Введите Новое Имя Персонажа.Не Забудьте После Смены Имени,Выйти Из Игры и Удалить Из Клиента Папку Cache!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Оплата Успешно Произведена Сделайте Логаут и Введите Новое Имя Персонажа.Не Забудьте После Смены Имени,Выйти Из Игры и Удалить Из Клиента Папку Cache!');
INSERT INTO `trinity_string` VALUES (40007,'Оплата Успешно Произведена Сделайте Логаут и Измените Внешность Персонажа.Не Забудьте После Смены Внешности,Выйти Из Игры и Удалить Из Клиента Папку Cache!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Оплата Успешно Произведена Сделайте Логаут и Измените Внешность Персонажа.Не Забудьте После Смены Внешности,Выйти Из Игры и Удалить Из Клиента Папку Cache!');
INSERT INTO `trinity_string` VALUES (40008,'Оплата Успешно Произведена Сделайте Логаут и Измените Фракцию Персонажа.Не Забудьте После Смены Внешности,Выйти Из Игры и Удалить Из Клиента Папку Cache!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Оплата Успешно Произведена Сделайте Логаут и Измените Фракцию Персонажа.Не Забудьте После Смены Внешности,Выйти Из Игры и Удалить Из Клиента Папку Cache!');
INSERT INTO `trinity_string` VALUES (40009,'Вылечи меня!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Вылечи меня!');
INSERT INTO `trinity_string` VALUES (40010,'Выучить все навыки оружия и защиты.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Выучить все навыки оружия и защиты.');
INSERT INTO `trinity_string` VALUES (40011,'[Бафнуть] Слово силы: Стойкость',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Бафнуть] Слово силы: Стойкость');
INSERT INTO `trinity_string` VALUES (40012,'[Бафнуть] Благословение Королей',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Бафнуть] Благословение Королей');
INSERT INTO `trinity_string` VALUES (40013,'[Бафнуть] Знак дикой природы',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Бафнуть] Знак дикой природы');
INSERT INTO `trinity_string` VALUES (40014,'[Бафнуть] Чародейская гениальность Даларана',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Бафнуть] Чародейская гениальность Даларана');
INSERT INTO `trinity_string` VALUES (40015,'[Бафнуть] Великое Благословение могущества',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Бафнуть] Великое Благословение могущества');
INSERT INTO `trinity_string` VALUES (40016,'[Бафнуть] Благословение мудрости',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Бафнуть] Благословение мудрости');
INSERT INTO `trinity_string` VALUES (40017,'[Бафнуть] Шипы',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Бафнуть] Шипы');
INSERT INTO `trinity_string` VALUES (40018,'[Бафнуть] Божественный дух',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Бафнуть] Божественный дух');
INSERT INTO `trinity_string` VALUES (40019,'[Бафнуть] Защита от темной магии',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Бафнуть] Защита от темной магии');
INSERT INTO `trinity_string` VALUES (40020,'[Бафнуть] Выносливость',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Бафнуть] Выносливость');
INSERT INTO `trinity_string` VALUES (40021,'[Меню бафов] ->',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Меню бафов] ->');
INSERT INTO `trinity_string` VALUES (40022,'[Premium buff] ->',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Premium buff] ->');
INSERT INTO `trinity_string` VALUES (40023,'[Title] ->',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Title] ->');
INSERT INTO `trinity_string` VALUES (40024,'[test] ->',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[test] ->');
INSERT INTO `trinity_string` VALUES (40025,'[titlestest] ->',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[titlestest] ->');
INSERT INTO `trinity_string` VALUES (40026,'[sumki] ->',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[sumki] ->');
INSERT INTO `trinity_string` VALUES (40027,'[key] ->',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[key] ->');
INSERT INTO `trinity_string` VALUES (40028,'[kaput] ->',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[kaput] ->');
INSERT INTO `trinity_string` VALUES (40029,'<- [Вернутся в Главное меню]',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'<- [Вернутся в Главное меню]');
INSERT INTO `trinity_string` VALUES (40030,'[Меню Профессий] ->',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Меню Профессий] ->');
INSERT INTO `trinity_string` VALUES (40031,'[Меню Второстепенных профессий] ->',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Меню Второстепенных профессий] ->');
INSERT INTO `trinity_string` VALUES (40032,'[страница] ->',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[страница] ->');
INSERT INTO `trinity_string` VALUES (40033,'Сменить Имя персонажа.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Сменить Имя персонажа.');
INSERT INTO `trinity_string` VALUES (40034,'Сменить Внешность персонажа.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Сменить Внешность персонажа.');
INSERT INTO `trinity_string` VALUES (40035,'Сменить Фракцию персонажа.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Сменить Фракцию персонажа.');
INSERT INTO `trinity_string` VALUES (40036,'[Бафнуть] Берсерк.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Бафнуть] Берсерк.');
INSERT INTO `trinity_string` VALUES (40037,'[Бафнуть] Эгида Рагнароса.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Бафнуть] Эгида Рагнароса.');
INSERT INTO `trinity_string` VALUES (40038,'[Бафнуть] Защита Нелтариона.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Бафнуть] Защита Нелтариона.');
INSERT INTO `trinity_string` VALUES (40039,'[Бафнуть] Благословение Адалла.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Бафнуть] Благословение Адалла.');
INSERT INTO `trinity_string` VALUES (40040,'[Бафнуть] Критическое срабатывание.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Бафнуть] Критическое срабатывание.');
INSERT INTO `trinity_string` VALUES (40041,'[Бафнуть] Благословение мистера Пинчи.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Бафнуть] Благословение мистера Пинчи.');
INSERT INTO `trinity_string` VALUES (40042,'[Бафнуть] Прозрачность.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Бафнуть] Прозрачность.');
INSERT INTO `trinity_string` VALUES (40043,'Получить звание Дженкинс.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Получить звание Дженкинс.');
INSERT INTO `trinity_string` VALUES (40044,'Получить звание Безумно Влюбленный.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Получить звание Безумно Влюбленный.');
INSERT INTO `trinity_string` VALUES (40045,'Получить звание Весельчак.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Получить звание Весельчак.');
INSERT INTO `trinity_string` VALUES (40046,'Получить звание Повелитель Скоробеев.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Получить звание Повелитель Скоробеев.');
INSERT INTO `trinity_string` VALUES (40047,'Получить звание Чудесный.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Получить звание Чудесный.');
INSERT INTO `trinity_string` VALUES (40048,'Получить звание Покоритель Обсидианового святилища.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Получить звание Покоритель Обсидианового святилища.');
INSERT INTO `trinity_string` VALUES (40049,'[Превратить] Гном, мужчина.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Превратить] Гном, мужчина.');
INSERT INTO `trinity_string` VALUES (40050,'[Превратить] Гном, женщина.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Превратить] Гном, женщина.');
INSERT INTO `trinity_string` VALUES (40051,'[Превратить] Человек, женщина.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Превратить] Человек, женщина.');
INSERT INTO `trinity_string` VALUES (40052,'[Превратить] Человек, мужчина.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Превратить] Человек, мужчина.');
INSERT INTO `trinity_string` VALUES (40053,'[Превратить] Эльф Крови, мужчина.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Превратить] Эльф Крови, мужчина.');
INSERT INTO `trinity_string` VALUES (40054,'[Превратить] Эльф Крови, женщина.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Превратить] Эльф Крови, женщина.');
INSERT INTO `trinity_string` VALUES (40055,'[Превратить] Таурен, мужчина.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Превратить] Таурен, мужчина.');
INSERT INTO `trinity_string` VALUES (40056,'[Превратить] Таурен, женщина.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'[Превратить] Таурен, женщина.');
INSERT INTO `trinity_string` VALUES (40057,'|TInterface\\icons\\Trade_Alchemy:40:40:-14|t Изучить Алхимию.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'|TInterface\\icons\\Trade_Alchemy:40:40:-14|t Изучить Алхимию.');
INSERT INTO `trinity_string` VALUES (40058,'|TInterface\\icons\\Trade_BlackSmithing:40:40:-14|t Изучить Кузнечное Дело.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'|TInterface\\icons\\Trade_BlackSmithing:40:40:-14|t Изучить Кузнечное Дело.');
INSERT INTO `trinity_string` VALUES (40059,'|TInterface\\icons\\Trade_Engraving:40:40:-14|t Изучить Наложение Чар.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'|TInterface\\icons\\Trade_Engraving:40:40:-14|t Изучить Наложение Чар.');
INSERT INTO `trinity_string` VALUES (40060,'|TInterface\\icons\\Trade_Engineering:40:40:-14|t Изучить Инженерное дело.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'|TInterface\\icons\\Trade_Engineering:40:40:-14|t Изучить Инженерное дело.');
INSERT INTO `trinity_string` VALUES (40061,'|TInterface\\icons\\Trade_Herbalism:40:40:-14|t Изучить Травничество.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'|TInterface\\icons\\Trade_Herbalism:40:40:-14|t Изучить Травничество.');
INSERT INTO `trinity_string` VALUES (40062,'|TInterface\\icons\\INV_Inscription_Tradeskill01:40:40:-14|t Изучить Начертание.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'|TInterface\\icons\\INV_Inscription_Tradeskill01:40:40:-14|t Изучить Начертание.');
INSERT INTO `trinity_string` VALUES (40063,'|TInterface\\icons\\INV_Misc_Gem_02:40:40:-14|t Изучить Ювелирное дело.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'|TInterface\\icons\\INV_Misc_Gem_02:40:40:-14|t Изучить Ювелирное дело.');
INSERT INTO `trinity_string` VALUES (40064,'|TInterface\\icons\\Trade_LeatherWorking:40:40:-14|t Изучить Кожевничество.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'|TInterface\\icons\\Trade_LeatherWorking:40:40:-14|t Изучить Кожевничество.');
INSERT INTO `trinity_string` VALUES (40065,'|TInterface\\icons\\Trade_Mining:40:40:-14|t Изучить Горное дело.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'|TInterface\\icons\\Trade_Mining:40:40:-14|t Изучить Горное дело.');
INSERT INTO `trinity_string` VALUES (40066,'|TInterface\\icons\\INV_Misc_Pelt_Wolf_01:40:40:-14|t Изучить Снятие шкур.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'|TInterface\\icons\\INV_Misc_Pelt_Wolf_01:40:40:-14|t Изучить Снятие шкур.');
INSERT INTO `trinity_string` VALUES (40067,'|TInterface\\icons\\Trade_Tailoring:40:40:-14|t Изучить Портное дело.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'|TInterface\\icons\\Trade_Tailoring:40:40:-14|t Изучить Портное дело.');
INSERT INTO `trinity_string` VALUES (40068,'Изучить Верховую Езду.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Изучить Верховую Езду.');
INSERT INTO `trinity_string` VALUES (40069,'|TInterface\\icons\\INV_Misc_Food_15:40:40:-14|t Изучить Кулинарию.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'|TInterface\\icons\\INV_Misc_Food_15:40:40:-14|t Изучить Кулинарию.');
INSERT INTO `trinity_string` VALUES (40070,'|TInterface\\icons\\Spell_Holy_SealOfSacrifice:40:40:-14|t Изучить Первую помощь.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'|TInterface\\icons\\Spell_Holy_SealOfSacrifice:40:40:-14|t Изучить Первую помощь.');
INSERT INTO `trinity_string` VALUES (40071,'Изучить Рыбную ловлю.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Изучить Рыбную ловлю.');
INSERT INTO `trinity_string` VALUES (40072,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1');
INSERT INTO `trinity_string` VALUES (40073,'2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2');
INSERT INTO `trinity_string` VALUES (40074,'3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'3');
INSERT INTO `trinity_string` VALUES (40075,'4',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'4');
INSERT INTO `trinity_string` VALUES (40076,'5',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'5');
INSERT INTO `trinity_string` VALUES (40077,'6',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'6');
INSERT INTO `trinity_string` VALUES (40078,'7',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'7');
INSERT INTO `trinity_string` VALUES (40079,'8',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'8');
INSERT INTO `trinity_string` VALUES (40080,'9',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'9');
INSERT INTO `trinity_string` VALUES (40081,'Король Лич ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Король Лич ');
INSERT INTO `trinity_string` VALUES (40082,'Огонек     ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Огонек     ');
INSERT INTO `trinity_string` VALUES (40083,'Лорд Каззак',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Лорд Каззак');
INSERT INTO `trinity_string` VALUES (40084,'Леокк      ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Леокк      ');
INSERT INTO `trinity_string` VALUES (40085,'Таддиус    ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Таддиус    ');
INSERT INTO `trinity_string` VALUES (40086,'Прелесть   ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Прелесть   ');
INSERT INTO `trinity_string` VALUES (40087,'Паук       ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Паук       ');
INSERT INTO `trinity_string` VALUES (40088,'Сапфирон   ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Сапфирон   ');
INSERT INTO `trinity_string` VALUES (40089,'Нот Чумной ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Нот Чумной ');
INSERT INTO `trinity_string` VALUES (40090,'Кель Тузед ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Кель Тузед ');
INSERT INTO `trinity_string` VALUES (40091,'КельТалас  ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'КельТалас  ');
INSERT INTO `trinity_string` VALUES (40092,'Ктун       ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Ктун       ');
INSERT INTO `trinity_string` VALUES (40093,'Тралл      ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Тралл      ');
INSERT INTO `trinity_string` VALUES (40094,'Сильвана   ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Сильвана   ');
INSERT INTO `trinity_string` VALUES (40095,'Алекстраза ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Алекстраза ');
INSERT INTO `trinity_string` VALUES (40096,'Король Ринн',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Король Ринн');
INSERT INTO `trinity_string` VALUES (40097,'Молганис   ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Молганис   ');
INSERT INTO `trinity_string` VALUES (40098,'Алекстраза ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Алекстраза ');
INSERT INTO `trinity_string` VALUES (40099,'Сакролаш   ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Сакролаш   ');
INSERT INTO `trinity_string` VALUES (40100,'Утгард Воин',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Утгард Воин');
INSERT INTO `trinity_string` VALUES (40101,'Упырь      ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Упырь      ');
INSERT INTO `trinity_string` VALUES (40102,'Скелет     ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Скелет     ');
INSERT INTO `trinity_string` VALUES (40103,'Скелет2   ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Скелет2   ');
INSERT INTO `trinity_string` VALUES (40104,'Скелет3   ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Скелет3   ');
INSERT INTO `trinity_string` VALUES (40105,'Пудж       ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Пудж       ');
INSERT INTO `trinity_string` VALUES (40106,'Скелет4   ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Скелет4   ');
INSERT INTO `trinity_string` VALUES (40107,'ВестникСмер',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ВестникСмер');
INSERT INTO `trinity_string` VALUES (40108,'РыцарьСмерт',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'РыцарьСмерт');
INSERT INTO `trinity_string` VALUES (40109,'Маг        ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Маг        ');
INSERT INTO `trinity_string` VALUES (40110,'Голум      ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Голум      ');
INSERT INTO `trinity_string` VALUES (40111,'Красный бес',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Красный бес');
INSERT INTO `trinity_string` VALUES (40112,'Древень    ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Древень    ');
INSERT INTO `trinity_string` VALUES (40113,'Синий бес  ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Синий бес  ');
INSERT INTO `trinity_string` VALUES (40114,'Огр        ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Огр        ');
INSERT INTO `trinity_string` VALUES (40115,'Демон Голов',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Демон Голов');
INSERT INTO `trinity_string` VALUES (40116,'Дреней     ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Дреней     ');
INSERT INTO `trinity_string` VALUES (40117,'Гидра      ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Гидра      ');
INSERT INTO `trinity_string` VALUES (40118,'Колосс     ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Колосс     ');
INSERT INTO `trinity_string` VALUES (40119,'Бес        ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Бес        ');
INSERT INTO `trinity_string` VALUES (40120,'Красный Орк',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Красный Орк');
INSERT INTO `trinity_string` VALUES (40121,'ЗанзилЧумно',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ЗанзилЧумно');
INSERT INTO `trinity_string` VALUES (40122,'Волк       ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Волк       ');
INSERT INTO `trinity_string` VALUES (40123,'Подобие    ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Подобие    ');
INSERT INTO `trinity_string` VALUES (40124,'Эльф       ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Эльф       ');
INSERT INTO `trinity_string` VALUES (40125,'Злобень    ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Злобень    ');
INSERT INTO `trinity_string` VALUES (40126,'Призрак    ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Призрак    ');
INSERT INTO `trinity_string` VALUES (40127,'Мароуз     ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Мароуз     ');
INSERT INTO `trinity_string` VALUES (40128,'Злобныйприз',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Злобныйприз');