INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60758,0,0,'Вам нечего здесь делать. Убирайтесь, пока живы!',14,0,100,1,0,0,0,0,'Comment');
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60758,1,0,'Ярость наполняет меня!',14,0,100,1,0,0,0,0,'Comment');
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60758,2,0,'Слуги мои, помогите!',14,0,100,1,0,0,0,0,'Comment');
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60758,3,0,'Этим всё и закончится!',14,0,100,1,0,0,0,0,'Comment');
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60758,4,0,'На этот раз... вам повезло...!',14,0,100,1,0,0,0,0,'Comment');

INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60759,0,0,'Я проморожу вас насквозь!',14,0,100,1,0,0,0,0,'Comment');
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60759,1,0,'Ещё одна бесполезная ледышка!',14,0,100,1,0,0,0,0,'Comment');
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60759,2,0,'Но! Я же был бессмертен...',14,0,100,1,0,0,0,0,'Comment');
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60759,3,0,'Кожа Стража льда Алкида покрывается коркой льда',14,0,100,1,0,0,0,0,'Comment');

INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60760,0,0,'Вам не следовало сюда приходить! Это место станет вашей могилой!',14,0,100,1,0,0,0,0,'Comment');
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60760,1,0,'Стража земли Акрилия наполняют силы земли',14,0,100,1,0,0,0,0,'Comment');
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60760,2,0,'Отправляйся в землю!',14,0,100,1,0,0,0,0,'Comment');
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60760,3,0,'Мать земля, помо... ох...',14,0,100,1,0,0,0,0,'Comment');

INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60761,0,0,'Гости? Неожиданно...',14,0,100,1,0,0,0,0,'Comment');
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60761,1,0,'О да..! Я чувствую как ваша ярость наполняет меня!',14,0,100,1,0,0,0,0,'Comment');
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60761,2,0,'Посмотрите на души тех, кто был здесь до вас.',14,0,100,1,0,0,0,0,'Comment');
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60761,3,0,'Твоя душа пополнит мою армию!',14,0,100,1,0,0,0,0,'Comment');
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES (60761,4,0,'Я слишком стар для таких битв...',14,0,100,1,0,0,0,0,'Comment');
