INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('761', '0', '8', '-1', '1208', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('836', '0', '8', '-1', '1007', '0', '8', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('951', '0', '8', '-1', '1093', '0', '0', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('1128', '0', '8', '-1', '1150', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('2071', '0', '8', '-1', '18084', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('5014', '0', '8', '-1', '6429', '0', '0', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('1267', '0', '8', '-1', '6359', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('1268', '0', '8', '-1', '2357', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('1269', '0', '8', '-1', '6367', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('1321', '0', '8', '-1', '6335', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('1400', '0', '8', '-1', '6418', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('1402', '0', '8', '-1', '6334', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('1533', '0', '8', '-1', '6358', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('1612', '0', '8', '-1', '6368', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('1649', '0', '8', '-1', '1483', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('1704', '0', '8', '-1', '1504', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('1851', '0', '8', '-1', '6340', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('2688', '0', '8', '-1', '6417', '0', '3', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('3441', '0', '8', '-1', '2947', '0', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('3507', '0', '8', '-1', '983', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('3768', '0', '8', '-1', '6326', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('3773', '0', '8', '-1', '18084', '0', '7', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('4427', '0', '8', '-1', '6270', '0', '7', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('5015', '0', '8', '-1', '6429', '0', '0', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('5031', '2', '8', '-1', '5536', '17', '1', '1');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('5041', '0', '8', '-1', '6423', '0', '0', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('5045', '0', '8', '-1', '6411', '0', '0', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('5049', '0', '8', '-1', '6405', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('5223', '0', '8', '-1', '1262', '0', '1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('5227', '0', '8', '-1', '1262', '0', '1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('5228', '0', '8', '-1', '6007', '0', '1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('5406', '0', '8', '-1', '6007', '0', '1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('5407', '0', '8', '-1', '6007', '0', '1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('6213', '0', '8', '-1', '4717', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('8493', '0', '8', '-1', '17288', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('11443', '0', '8', '-1', '2376', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('12440', '0', '8', '-1', '11947', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('12526', '0', '8', '-1', '9666', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('12729', '0', '8', '-1', '2533', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('16086', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('16102', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('16103', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('16104', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('16105', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('16106', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('16107', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('16108', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17162', '0', '8', '-1', '2760', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17163', '0', '8', '-1', '29131', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17827', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17828', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17829', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17830', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17883', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17884', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17885', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17888', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17889', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17890', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17891', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17892', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17893', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17894', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17895', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17896', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17897', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17898', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17899', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('18105', '0', '8', '-1', '30494', '0', '0', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('18106', '0', '8', '-1', '12206', '0', '0', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('18599', '0', '8', '-1', '36684', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('18666', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('18667', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('18668', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('18669', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22021', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22022', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22025', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22026', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22027', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22028', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22029', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22030', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22031', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22032', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22033', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22034', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22035', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22036', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22037', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22038', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22039', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22040', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22041', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22043', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22585', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22586', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22587', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22588', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('23245', '0', '8', '-1', '35738', '0', '0', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('23656', '0', '8', '-1', '34744', '0', '0', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('23699', '0', '8', '-1', '36460', '0', '0', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('23700', '0', '8', '-1', '31256', '0', '0', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('23701', '0', '8', '-1', '31257', '0', '0', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('23725', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('23727', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('23728', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('24491', '0', '8', '-1', '24591', '0', '0', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('24541', '0', '8', '-1', '3427', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29837', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29838', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29843', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29844', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29845', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29846', '0', '8', '-1', '36684', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29847', '0', '8', '-1', '36684', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29848', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29849', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29850', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29851', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29853', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29854', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29858', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29859', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29862', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29864', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29866', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29867', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29869', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29870', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('29873', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('30191', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('30195', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('30198', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('30199', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('30347', '0', '8', '-1', '8026', '0', '1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('30877', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('31167', '0', '8', '-1', '40372', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('31842', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('31844', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('31846', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('31847', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('31848', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('32775', '0', '8', '-1', '12310', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('32952', '0', '8', '-1', '7899', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('32965', '0', '8', '0', '45808', '0', '0', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('32966', '0', '8', '0', '20874', '0', '0', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('32967', '0', '8', '0', '45809', '0', '0', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('38306', '0', '8', '-1', '50629', '0', '8', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('38474', '0', '8', '-1', '41062', '0', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('38475', '0', '8', '-1', '41061', '0', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('38476', '0', '8', '-1', '41050', '0', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('38478', '0', '8', '-1', '41050', '0', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('38571', '0', '8', '0', '7374', '0', '4', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('39061', '0', '8', '0', '1103', '0', '4', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('39972', '0', '8', '-1', '41062', '0', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('40774', '0', '8', '-1', '52745', '0', '-1', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('46845', '0', '8', '-1', '8625', '0', '4', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('46846', '0', '8', '-1', '8625', '0', '4', '0');

INSERT INTO `creature_template2` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `dmgschool`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `DamageModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `spell_school_immune_mask`, `flags_extra`, `ScriptName`, `StringId`, `VerifiedBuild`) VALUES (90139, 0, 0, 0, 0, 0, 22918, 0, 22918, 0, 'Боньк', '', '', 0, 85, 85, 2, 35, 4224, 2, 2, 1, 2, 0, 2000, 2000, 1, 1, 2, 64, 2048, 0, 0, 4, 12, 0, 0, 0, 0, 0, 1000, 1000, '', 0, 1, 600, 300, 10, 1, 1, 0, 0, 1, 0, 0, 2, '', NULL, 12340);
INSERT INTO `creature_template2` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `dmgschool`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `DamageModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `spell_school_immune_mask`, `flags_extra`, `ScriptName`, `StringId`, `VerifiedBuild`) VALUES (90140, 0, 0, 0, 0, 0, 22918, 0, 22918, 0, 'Боньк', '', '', 0, 85, 85, 2, 35, 4224, 2, 2, 1, 2, 0, 2000, 2000, 1, 1, 2, 64, 2048, 0, 0, 4, 12, 0, 0, 0, 0, 0, 1000, 1000, '', 0, 1, 600, 300, 10, 1, 1, 0, 0, 1, 0, 0, 2, '', NULL, 12340);


INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 761, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 836, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 951, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 1128, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 2071, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 5014, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 1267, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 1268, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 1269, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 1321, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 1400, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 1402, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 1533, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 1612, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 1649, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 1704, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 1851, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 2688, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 3441, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 3507, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 3768, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 3773, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 4427, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 5015, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 5031, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 5041, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 5045, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 5049, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 5223, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 5227, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 5228, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 5406, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 5407, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 6213, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 8493, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 11443, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 12440, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 12526, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 12729, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 16086, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 16102, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 16103, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 16104, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 16105, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 16106, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 16107, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 16108, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17162, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17163, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17827, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17828, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17829, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17830, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17883, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17884, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17885, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17888, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17889, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17890, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17891, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17892, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17893, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17894, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17895, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17896, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17897, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17898, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 17899, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 18105, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 18106, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 18599, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 18666, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 18667, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 18668, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 18669, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22021, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22022, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22025, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22026, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22027, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22028, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22029, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22030, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22031, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22032, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22033, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22034, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22035, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22036, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22037, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22038, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22039, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22040, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22041, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22043, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22585, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22586, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22587, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 22588, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 23245, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 23656, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 23699, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 23700, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 23701, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 23725, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 23727, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 23728, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 24491, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 24541, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29837, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29838, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29843, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29844, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29845, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29846, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29847, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29848, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29849, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29850, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29851, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29853, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29854, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29858, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29859, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29862, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29864, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29866, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29867, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29869, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29870, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 29873, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 30191, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 30195, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 30198, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 30199, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 30347, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 30877, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 31167, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 31842, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 31844, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 31846, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 31847, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 31848, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 32775, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 32952, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 32965, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 32966, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90139, 0, 32967, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90140, 0, 38306, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90140, 0, 38474, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90140, 0, 38475, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90140, 0, 38476, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90140, 0, 38478, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90140, 0, 38571, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90140, 0, 39061, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90140, 0, 39972, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90140, 0, 40774, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90140, 0, 46845, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (90140, 0, 46846, 0, 0, 2, 0);