INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('12786', '2', '4', '-1', '23253', '13', '2', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('12788', '2', '4', '-1', '23255', '13', '2', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('12883', '2', '4', '-1', '23357', '13', '2', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('12934', '2', '4', '-1', '23448', '13', '2', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('13220', '2', '4', '-1', '23792', '13', '2', '7');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17040', '2', '4', '-1', '28866', '13', '2', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('17041', '2', '4', '-1', '28867', '13', '2', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('19359', '2', '4', '-1', '31861', '13', '1', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('19404', '2', '4', '-1', '31935', '13', '2', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('19916', '2', '4', '-1', '11958', '13', '2', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('20738', '2', '4', '-1', '33181', '13', '1', '7');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22213', '2', '4', '-1', '34559', '13', '2', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22341', '2', '4', '-1', '34820', '13', '2', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('22724', '2', '4', '-1', '35129', '13', '2', '1');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('23583', '2', '4', '-1', '36382', '13', '1', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('23708', '2', '4', '-1', '36467', '13', '2', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('23906', '2', '4', '-1', '36631', '13', '2', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('24332', '2', '4', '-1', '37031', '13', '2', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('24333', '2', '4', '-1', '37034', '13', '2', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('25646', '2', '4', '-1', '7468', '13', '2', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('25663', '2', '4', '-1', '37589', '13', '2', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26589', '2', '4', '-1', '5203', '13', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26590', '2', '4', '-1', '22118', '13', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26591', '2', '4', '-1', '22118', '13', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26592', '2', '4', '-1', '22118', '13', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26593', '2', '4', '-1', '22118', '13', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26594', '2', '4', '-1', '22118', '13', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26595', '2', '4', '-1', '22118', '13', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26596', '2', '4', '-1', '22118', '13', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26597', '2', '4', '-1', '22118', '13', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26598', '2', '4', '-1', '22118', '13', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26599', '2', '4', '-1', '22118', '13', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26600', '2', '4', '-1', '22118', '13', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26601', '2', '4', '-1', '22118', '13', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26784', '2', '4', '-1', '22118', '21', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26785', '2', '4', '-1', '22118', '21', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26786', '2', '4', '-1', '22118', '21', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26787', '2', '4', '-1', '22118', '21', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26788', '2', '4', '-1', '22118', '21', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26789', '2', '4', '-1', '22118', '21', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26790', '2', '4', '-1', '22118', '21', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26791', '2', '4', '-1', '22118', '21', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26793', '2', '4', '-1', '22118', '21', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26794', '2', '4', '-1', '22118', '21', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26795', '2', '4', '-1', '22118', '21', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26796', '2', '4', '-1', '22118', '21', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('26797', '2', '4', '-1', '22118', '21', '2', '0');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('50557', '2', '4', '-1', '58909', '21', '1', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('50580', '2', '4', '-1', '58908', '13', '1', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('50752', '2', '4', '4', '64049', '13', '1', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('50753', '2', '4', '-1', '64050', '13', '2', '2');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('52015', '2', '4', '-1', '54760', '13', '1', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('52037', '2', '4', '-1', '64910', '21', '2', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('52042', '2', '4', '-1', '64994', '13', '1', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('53096', '2', '4', '-1', '60714', '21', '1', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('53785', '2', '4', '4', '66474', '13', '1', '3');
INSERT INTO `item_template2` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`,`displayid`,`inventorytype`,`material`,`sheath`)VALUES ('54555', '2', '4', '4', '67187', '17', '1', '3');

INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 12786, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 12788, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 12883, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 12934, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 13220, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 17040, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 17041, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 19359, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 19404, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 19916, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 20738, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 22213, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 22341, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 22724, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 23583, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 23708, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 23906, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 24332, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 24333, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 25646, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 25663, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26589, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26590, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26591, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26592, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26593, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26594, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26595, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26596, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26597, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26598, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26599, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26600, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26601, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26784, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26785, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26786, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26787, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26788, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26789, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26790, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26791, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26793, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26794, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26795, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26796, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 26797, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 50557, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 50580, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 50752, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 50753, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 52015, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 52037, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 52042, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 53096, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 53785, 0, 0, 2, 0);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES (60900, 0, 54555, 0, 0, 2, 0);

INSERT INTO `creature_template2` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `dmgschool`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `DamageModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `spell_school_immune_mask`, `flags_extra`, `ScriptName`, `StringId`, `VerifiedBuild`) VALUES (90134, 0, 0, 0, 0, 0, 23079, 0, 0, 0, 'Самоделкина', NULL, NULL, 0, 80, 80, 2, 7, 0, 1, 1.42857, 1, 0, 0, 2000, 2000, 1, 1, 1, 32768, 2048, 0, 0, 7, 0, 0, 4624, 0, 0, 0, 0, 0, '', 0, 1, 4, 600, 1, 60, 1, 0, 0, 1, 0, 0, 65536, 'npc_guard_generic', NULL, 12340);

INSERT INTO `creature_equip_template` (`CreatureID`, `ID`, `ItemID1`, `ItemID2`, `ItemID3`, `VerifiedBuild`) VALUES (90134, 1, 25646, 17041, 0, 0);

INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `MountCreatureID`, `StandState`, `AnimTier`, `VisFlags`, `SheathState`, `PvPFlags`, `emote`, `visibilityDistanceType`, `auras`) VALUES (90134, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, NULL);
